# Generated by Django 4.2.5 on 2023-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("console_output", models.TextField(blank=True, default="")),
            ],
        ),
    ]
