# Generated by Django 4.2.5 on 2023-10-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0004_logentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="running",
            new_name="is_running",
        ),
    ]
