# Generated by Django 4.2.5 on 2023-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0005_rename_running_block_is_running"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="status",
            field=models.CharField(default="NOT RUNNING", max_length=255),
        ),
    ]
