# Generated by Django 4.2.5 on 2023-10-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("connector", "0007_remove_block_block_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="output_data",
        ),
    ]
